---
scenario:
  name: with_ec2
driver:
  name: ec2
platforms:
  - name: prereqs1-centos7
    image: ami-9887c6e7
    region: us-east-1
    instance_type: t2.micro
    ssh_user: centos
    groups:
      - prereqsgroup
  - name: prereqs1-rhel7
    image: ami-011b3ccf1bd6db744
    region: us-east-1
    instance_type: t2.micro
    groups:
      - prereqsgroup
  # - name: prereqs1-rhel8
  #   image: ami-0551d2acb56d6e88c
  #   region: us-east-1
  #   instance_type: t2.micro
  #   groups:
  #     - prereqsgroup
provisioner:
  name: ansible
  inventory:
    host_vars:
      prereqs1-rhel8:
        ansible_python_interpreter: "/usr/libexec/platform-python" #hack hack hack! Switch to official once RH releases the packages
    group_vars:
      prereqsgroup:
        dcos:
          selinux_mode: enforcing
  lint:
    name: ansible-lint
    enabled: False
lint:
  name: yamllint
  enabled: False
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: False
