---
- name: Wait for instances to become reachable
  hosts: linux
  gather_facts: no
  tasks:
    - name: Wait for instances to become reachable
      wait_for_connection:
        delay: 10
        sleep: 10
        timeout: 120

- name: Collect DC/OS versions
  hosts: linux
  gather_facts: no
  tasks:
    - name: Collect DC/OS versions
      setup:


- name: DC/OS Requirements
  hosts: linux
  gather_facts: no
  become: true
  tasks:
    - include_role:
        name: dcos_requirements
    - include_role:
        name: DCOS.gpu


- name: Setup and configure BOOTSTRAP nodes
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: DCOS.bootstrap


- name: Setup and configure MASTER nodes
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master

- name: Setup and configure AGENT nodes (Linux)
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
      tags:
        - linux_setup

- name: Setup and configure AGENT nodes (Windows)
  hosts: win_agents
  gather_facts: no
  tasks:
    - include_role:
        name: DCOS.agent_windows
