---
- name: Wait for instances to become reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Save target host IP
      set_fact:
        target_host: "{{ ansible_host }}"
        target_port: "{{ansible_port | default (22)}}"
    - name: Wait for instances to become reachable
      wait_for:
        port: "{{target_port}}"
        host: "{{target_host}}"
        sleep: 10
        timeout: 120
        state: started
      delegate_to: localhost

- name: Collect DC/OS versions
  hosts: all
  tasks:
    - name: Collect DC/OS versions
      setup:

- name: DC/OS Requirements
  hosts: all
  become: true
  tasks:
    - include_role:
        name: dcos_requirements
    - include_role:
        name: dcos_gpu

- name: "Setup and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: dcos_bootstrap

- name: "Setup and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: dcos_master

- name: "Setup and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: dcos_agent
