---
- name: Wait for instances to become reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for instances to become reachable
      wait_for_connection:
        delay: 10
        sleep: 10
        timeout: "{{ connection_timeout | default(120) }}"

- name: Collect DC/OS versions
  hosts: all
  tasks:
    - name: Collect DC/OS versions
      setup:

- name: DC/OS Requirements
  hosts: all
  tasks:
    - include_role:
        name: dcos_requirements
    - include_role:
        name: dcos_gpu

- name: Setup and configure BOOTSTRAP nodes
  hosts: bootstraps
  tasks:
    - include_role:
        name: dcos_bootstrap

- name: Setup and configure MASTER nodes
  hosts: masters
  serial: 1
  tasks:
    - include_role:
        name: dcos_master

- name: Setup and configure AGENT nodes (Linux)
  hosts: agents
  tasks:
    - include_role:
        name: dcos_agent
