---
- name: Wait for instances to become reachable
  hosts: all
  tasks:
    - name: Wait for instances to respond to pings
      wait_for_connection:

    - name: Wait for port 22 to be open
      wait_for:
        port: 22
        sleep: 1
        timeout: 660
        delay: 60
        connect_timeout: 5
        state: started

- name: Collect DC/OS versions
  hosts: all
  tasks:
    - name: Collect DC/OS versions
      setup:

- name: DC/OS Requirements
  hosts: all
  become: true
  tasks:
    - include_role:
        name: DCOS.requirements

- name: "Setup and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: DCOS.bootstrap

- name: "Setup and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master

- name: "Setup and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
