---
- name: "Determine if system is CoreOS/Flatcar Linux"
  set_fact:
    is_flatcar: "{{ ansible_distribution == 'Coreos' or ansible_distribution == 'Flatcar Container Linux by Kinvolk' or ansible_distribution == 'Flatcar Linux by Kinvolk' }}"
  changed_when: false


- include_tasks: EL.yml
  when: not is_flatcar
