---
- name: "NVIDIA Gpu - CentOS 7"
  include_tasks: nvidia-gpu-CentOS7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '7'
- name: "NVIDIA Gpu - RHEL 7"
  include_tasks: nvidia-gpu-RHEL7.yml
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
