---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  vars:
    ssh_user: ec2-user
    ssh_port: 22
    spot_price_max_calc: 5

    admin_ip: "{{ lookup('url', 'http://whatismyip.akamai.com') }}"
    security_group_name: "molecule_{{ lookup('env', 'HOSTNAME') | default(lookup('env', 'USER') | to_uuid, true) }}"
    security_group_description: Security group for testing Molecule
    security_group_rules:
      - proto: tcp
        from_port: "{{ ssh_port }}"
        to_port: "{{ ssh_port }}"
        cidr_ip: "{{ admin_ip }}/32"
      - proto: icmp
        from_port: 8
        to_port: -1
        cidr_ip: "{{ admin_ip }}/32"
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: "172.31.0.0/16"
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: "0.0.0.0/0"

    keypair_name: "molecule_key_{{ lookup('env', 'HOSTNAME') | default(lookup('env', 'USER') | to_uuid, true) }}"
    keypair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
  tasks:
    - debug:
        var: molecule_yml.platforms
    - name: Create security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: "{{ security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"
        region: "{{ molecule_yml.platforms[0].region }}"
      register: security_group

    - name: Create keypair
      ec2_key:
        name: "{{ keypair_name }}"
        region: "{{ molecule_yml.platforms[0].region }}"
      register: keypair

    - name: Persist the keypair
      copy:
        dest: "{{ keypair_path }}"
        content: "{{ keypair.key.private_key }}"
        mode: 0600
      when: keypair.changed

    - name: Create molecule instance(s)
      ec2:
        key_name: "{{ keypair_name }}"
        image: "{{ item.image }}"
        region: "{{ item.region }}"
        zone: "{{ item.zone|default(omit) }}"
        instance_initiated_shutdown_behavior: terminate
        instance_type: "{{ item.instance_type }}"
        spot_price: "{{ item.spot_price | ternary(item.spot_price, omit) if item.spot_price is defined else spot_price_max_calc }}"
        group: "{{ security_group_name }}"
        volumes:
          - device_name: /dev/sda1
            volume_size: 20
            volume_type: gp2
            delete_on_termination: yes
        instance_tags:
          Name: "molecule {{ item.name }}"
          instance: "{{ item.name }}"
          molecule_region: "{{ item.region }}"
          molecule_ssh_user: "{{ item.ssh_user | default(ssh_user) }}"
        wait: yes
        exact_count: 1
        count_tag:
          instance: "{{ item.name }}"
      register: server
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict:
          {
            "instance": "{{ item.instances[0].tags.instance }}",
            "region": "{{ item.instances[0].tags.molecule_region }}",
            "address": "{{ item.instances[0].public_ip }}",
            "user": "{{ item.instances[0].tags.molecule_ssh_user }}",
            "port": "{{ ssh_port }}",
            "identity_file": "{{ keypair_path }}",
            "instance_ids": "{{ item.instance_ids }}",
          }
      with_items: "{{ ec2_jobs.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ item.port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 60
        timeout: 320
      with_items: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"

    - name: Wait for boot process to finish
      pause:
        seconds: 2
