---
- name: Collect facts for hostvars for autoamtic master IP detection in this playbook
  hosts: all
  tasks:
    - name: Collect
      setup: {}
- name: Set open checksum and url
  hosts: localhost
  tasks:
    - name: OSS DC/OS
      set_fact:
        test_initial_download: "https://downloads.dcos.io/dcos/testing/pull/7017/dcos_generate_config.sh"
        test_initial_download_checksum: ""
        test_initial_commit: "8c6ec915d7653a0fd288148c391454097f3f4bf2"
        test_initial_version: "2.1.0-dev"
        test_initial_download_win: "https://downloads.dcos.io/dcos/testing/pull/7017/windows/dcos_generate_config_win.sh"
        test_upgrade_download: "https://downloads.dcos.io/dcos/testing/pull/7111/dcos_generate_config.sh"
        test_upgrade_download_checksum: ""
        test_upgrade_commit: "820bb47e8e28ffac330bc3f99a63b359e1653e0d"
        test_upgrade_version: "2.1.0-dev"
        test_upgrade_download_win: "https://downloads.dcos.io/dcos/testing/pull/7111/windows/dcos_generate_config_win.sh"
      when: not dcos['enterprise_dcos']
    - name: EE DC/OS
      set_fact:
        test_initial_download: "https://downloads.mesosphere.com/dcos-enterprise/testing/pull/7555/commit/f5366468627b9ca79c02b746d481b101f30a876d/dcos_generate_config.ee.sh"
        test_initial_download_checksum: ""
        test_initial_commit: "f5366468627b9ca79c02b746d481b101f30a876d"
        test_initial_version: "2.1.0-dev"
        test_initial_download_win: "https://downloads.mesosphere.com/dcos-enterprise/testing/pull/7555/commit/f5366468627b9ca79c02b746d481b101f30a876d/windows/dcos_generate_config_win.ee.sh"
        test_upgrade_download: "https://downloads.mesosphere.io/dcos-enterprise/testing/pull/7643/commit/6118b9d3dff21dfd15b71893061f86b34a62d157/dcos_generate_config.ee.sh"
        test_upgrade_download_checksum: ""
        test_upgrade_commit: "6118b9d3dff21dfd15b71893061f86b34a62d157"
        test_upgrade_version: "2.1.0-dev"
        test_upgrade_download_win: "https://downloads.mesosphere.io/dcos-enterprise/testing/pull/7643/commit/6118b9d3dff21dfd15b71893061f86b34a62d157/windows/dcos_generate_config_win.ee.sh"
      when: dcos['enterprise_dcos']

- name: "Same-version-config update BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: dcos_bootstrap
  vars:
    dcos:
      download: "{{ hostvars['localhost'].test_upgrade_download }}"
      download_checksum: "{{ hostvars['localhost'].test_upgrade_download_checksum }}"
      download_win: "{{ hostvars['localhost'].test_upgrade_download_win }}"
      version: "{{ hostvars['localhost'].test_upgrade_version }}"
      image_commit: "{{ hostvars['localhost'].test_upgrade_commit }}"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        enable_windows_agents: true
        resolvers: [1.1.1.1, 8.8.8.8]

- name: "Same-version-config update MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: dcos_master
  vars:
    dcos:
      download: "{{ hostvars['localhost'].test_upgrade_download }}"
      download_checksum: "{{ hostvars['localhost'].test_upgrade_download_checksum }}"
      download_win: "{{ hostvars['localhost'].test_upgrade_download_win }}"
      version: "{{ hostvars['localhost'].test_upgrade_version }}"
      image_commit: "{{ hostvars['localhost'].test_upgrade_commit }}"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        enable_windows_agents: true
        resolvers: [1.1.1.1, 8.8.8.8]

- name: "Same-version-config update AGENT nodes"
  hosts: agents:!agents_windows
  tasks:
    - include_role:
        name: dcos_agent
  vars:
    dcos:
      download: "{{ hostvars['localhost'].test_upgrade_download }}"
      download_checksum: "{{ hostvars['localhost'].test_upgrade_download_checksum }}"
      download_win: "{{ hostvars['localhost'].test_upgrade_download_win }}"
      version: "{{ hostvars['localhost'].test_upgrade_version }}"
      image_commit: "{{ hostvars['localhost'].test_upgrade_commit }}"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        enable_windows_agents: true
        resolvers: [1.1.1.1, 8.8.8.8]
