---
- name: "Setup portable python if needed"
  hosts: needs_portable_python
  gather_facts: False
  tasks:
    - name: set inventory variables
      set_fact:
        ansible_python_interpreter: /home/core/bin/python
        pip_executable: /home/core/bin/pip
        needs_portable_python: yes
    - name: include python role
      include_role:
        name: dcos_python

- name: Collect facts for hostvars for autoamtic master IP detection in this playbook
  hosts: all
  tasks:
    - name: Collect
      setup: {}

- name: "Same-version-config update BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: dcos_bootstrap
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        resolvers: [1.1.1.1, 8.8.8.8]

- name: "Same-version-config update MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: dcos_master
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        resolvers: [1.1.1.1, 8.8.8.8]

- name: "Same-version-config update AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: dcos_agent
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        resolvers: [1.1.1.1, 8.8.8.8]
