---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: False
platforms:
  - name: prereqs1-centos7
    box: centos/7
    memory: 1024
    cpus: 1
    groups:
      - prereqsgroup
  - name: prereqs1-rhel7
    box: generic/rhel7
    memory: 1024
    cpus: 1
    groups:
      - prereqsgroup
  # - name: prereqs1-rhel8
  #   box: mesosphere-rhel/8beta
  #   memory: 1024
  #   cpus: 1
  #   groups:
  #     - prereqsgroup
provisioner:
  name: ansible
  inventory:
    host_vars:
      prereqs1-rhel8:
        ansible_python_interpreter: "/usr/libexec/platform-python" #hack hack hack! Switch to official once RH releases the packages:
    group_vars:
      prereqsgroup:
        dcos:
          selinux_mode: enforcing
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: False
