dcos_timesync: True
cloud_time_sync_package: chrony
onprem_time_sync_package: ntp
dcos_docker_pkgs:
  - docker-ce-19.03.13
  - docker-ce-cli-19.03.13
dcos_containerd_pkg_name: containerd.io-1.3.7
dcos_prereq_packages:
  - iptables
  - tar
  - xz
  - unzip
  - curl
  - ipset
  - net-tools # `ifconfig` has been a non documented requirement for 1.12.0,
  #             fixed with https://github.com/dcos/dcos/pull/3734
  - jq # not technically required by DC/OS but by this Ansible role for checks
