# The converge 'playbook.yml' invokes both an initial install and an upgrade, therefore
# it cannot be used for idempotence test, as it would downgrade (which would fail anyway)
# and then upgrade again. Below is a copy of the upgrading part, which should not trigger
# any changes in Ansible.

- name: "Upgrade and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: dcos_bootstrap
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        resolvers: [1.1.1.1]

- name: "Upgrade and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: dcos_master
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        resolvers: [1.1.1.1]

- name: "Upgrade and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: dcos_agent
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.default_ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.default_ipv4.address }}"]
        resolvers: [1.1.1.1]
